#! /bin/sh
sudo mknod console c 5 1
sudo mknod ttyS0 c 4 64
sudo ln -s ttyS0 tty
sudo mknod ttyS1 c 4 65
sudo mknod ttyS2 c 4 66
sudo mknod ttyS3 c 4 67
sudo mknod tty0 c 4 0
sudo mknod tty1 c 4 1
sudo mknod tty2 c 4 2
sudo mknod tty3 c 4 3
sudo mknod tty4 c 4 4
sudo mknod tty5 c 4 5
sudo mknod tty6 c 4 6
sudo mknod tty7 c 4 7
sudo mknod tty8 c 4 8
sudo mknod tty9 c 4 9

sudo mknod hda  b 3 0
sudo mknod hda1 b 3 1
sudo mknod hdb  b 3 64
sudo mknod hdb1 b 3 65
sudo mknod hdc  b 22 0
sudo mknod hdd  b 22 64
sudo mknod zero b 1 5

sudo mknod random c 1 8
sudo mknod urandom c 1 9

sudo mknod rtc c 10 135

sudo mknod psaux c 10 1
mkdir -p input
sudo mknod input/mouse0 c 13 32
sudo mknod input/mouse1 c 13 33
sudo mknod input/mice c 13 63
sudo mknod input/event0 c 13 64
sudo mknod input/event1 c 13 65

sudo mknod mem c 1 1
sudo mknod kmem c 1 2
sudo mknod null c 1 3
sudo mknod zero c 1 5
